### ISSUE TITLE
Instances don't mount full disk-space

### ISSUE THREAD

**Issue by krlng** [GoogleCloudPlatform/cloud-dataproc#55]
I setup a cluster using: 
`gcloud dataproc clusters create test --zone 'europe-west1-b' --subnet 'default' --worker-boot-disk-size '3TB' --master-boot-disk-size '1TB'`

the disk get created with the correct size, but if the configured size is bigger then 2TB (also the default), the volumes only get mounted with 2 TB:

```
gcloud compute ssh test-w-0 -- df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1       2.0T  3.5G  1.9T   1% /
udev             10M     0   10M   0% /dev
tmpfs           3.0G  8.4M  3.0G   1% /run
tmpfs           7.4G     0  7.4G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           7.4G     0  7.4G   0% /sys/fs/cgroup
tmpfs           1.5G     0  1.5G   0% /run/user/109
tmpfs           1.5G     0  1.5G   0% /run/user/110
tmpfs           1.5G     0  1.5G   0% /run/user/1000
```

Reducing the size to a smaller number works. I know that this worked a week ago.

**Comment by medb** [comment]
Per [GCE documentation](https://cloud.google.com/compute/docs/disks/create-root-persistent-disks) 2TB+ boot disks are not supported due to MBR partitions limitation:
> When you create your boot disk, limit the size to 2TB to account for the limitations of MBR partitions.

**Comment by krlng** [comment]
Well, this did work in the past. 

Is there any way to circumvent this limitation such as choosing another Image? As far as I know there is no possibility to mount multiple disks to a dataproc instance using the CLI. So probably the only way is to create multiple disks and mount those in the setup scripts?

**Comment by medb** [comment]
Not sure how it worked before, maybe you have used LocalSSDs? LocalSSDs are mounted as additional disks, in this way you can get more than 2TB of total disk space.

It's not advised to create PD bigger than 1.5TB per VM because of [PDs performance limitations](https://cloud.google.com/compute/docs/disks/performance). Generally, small VMs and 1.5 TB PDs should give you better performance than big VMs and PDs bigger than 1.5TB with the same cores to PD size ratio.

Yes, potentially, giving Dataproc cluster `cloud-scope`, creating additional PDs separately and mounting them from inside VMs during startup should work.
