### ISSUE TITLE
Remove prediction/eval from preprocessor

### ISSUE THREAD

**Issue by waprin** [GoogleCloudPlatform/cloud-dataproc#8]

**Comment by nkashy1** [comment]
To make the Spark portion of the application more consistent with the tf.Transform semantics, we should replace the existing modes (`train`, `evaluate`, `predict`) with the following two modes:

1. `analyze` - this will only perform artifact export. This is the first portion of the current `train` mode workflow (barring the export of the transformed dataset).

2. `transform` - this will use already-exported artifacts to transform a dataset. This is exactly what the current `evaluate` mode does.

**Comment by nkashy1** [comment]
The workflow after the change should begin by preparing artifacts from training data by running our script in `--mode analyze`

Subsequent to this, for now, we will prepare the training and evaluation data by running the script in `--mode transform` on the training and evaluation datasets.

The TensorFlow trainer can be trained using these artifacts, training dataset, and evaluation dataset.

There is a redundancy here in that we could just have TensorFlow apply the transformations instead of having to run them through Spark. The only reason we have this redundancy is that we wanted to show off `spark-tensorflow-connector`. If we relax this requirement, we would have a much better example wherein we simply load training and evaluation CSVs into TensorFlow using the artifacts to transform them. I am in favor of relaxing this dependency on `spark-tensorflow-connector` to make this Spark application much simpler. What do you think @waprin ?

**Comment by waprin** [comment]
@nkashy1 I am opposed to relaxing that requirement because it removes the main point of the sample. Also in what way is doing it in TF over Spark better?

**Comment by nkashy1** [comment]
@waprin : Just wanted to record our discussion from yesterday here.

As Eli pointed out, it's actually worse for training since you can do it on a single pass over training dataset in Spark and preprocessing would be applied once per epoch to the same data in TensorFlow.

**Comment by waprin** [comment]
Remaining items on this issue:

* Spark Transform needs to use the artifacts created by analyz eto replace missing integer values and replace categorical values by rank
* Streaming prediction transforms
* All the tests
