### ISSUE TITLE
[custom images]Not Support preview version number

### ISSUE THREAD

**Issue by howie** [GoogleCloudPlatform/cloud-dataproc#91]
According to this question [How to create a custom dataproc image based on a preview release](https://stackoverflow.com/questions/54786596/how-to-create-a-custom-dataproc-image-based-on-a-preview-release/54798262#54798262).

```
  # Old style images: 1.2.3
  # New style images: 1.2.3-deb8
  _VERSION_REGEX = re.compile(r"^\d+\.\d+\.\d+(-.{4})?$")
```
Only 1.4.0-deb9 can match the regex but 1.4.0-RC10-deb9 will not match.

**Comment by asasbru** [comment]
RC has problems setting custom label in

def set_custom_image_label(image_name, version, project_id, parsed=False):
  if not parsed:
    # version regex already checked in arg parser
    parsed_version = version.split(".")
    filter_arg = "--labels=goog-dataproc-version={}-{}-{}".format(
        parsed_version[0], parsed_version[1], parsed_version[2])
  else:
    # in this case, the version is already in the format of
    # <major>-<minor>-<subminor>
    filter_arg = "--labels=goog-dataproc-version={}".format(version)
  command = ["gcloud", "compute", "images", "add-labels",
             image_name, "--project", project_id, filter_arg]
   ...

ERROR: (gcloud.compute.images.add-labels) HTTPError 400: Invalid value for field 'labels': ''. Label value '1-4-0-RC8-deb9' violates format constraints. The value can only contain lowercase letters, numeric characters, underscores and dashes. The value can be at most 63 characters long. International characters are allowed.
Traceback (most recent call last):

You can avoid this error with: filter_arg.lower()

but then complains later when you create the cluster (at least from the console) because the tag is invalid. You can hack this writing an older valid version
